CREATE SCHEMA hotel_management_api_db;
USE hotel_management_api_db;

CREATE TABLE room (
ID INT AUTO_INCREMENT PRIMARY KEY,
Oda_Numarasi VARCHAR(10) UNIQUE NOT NULL,
Tip VARCHAR(50) NOT NULL,
Gecelik_Fiyat DECIMAL(10,2) NOT NULL,
Durum INT DEFAULT 0
);
CREATE TABLE reservation(
ID INT AUTO_INCREMENT PRIMARY KEY,
Oda_ID INT,
Musteri_Ad_Soyad VARCHAR(100) NOT NULL,
Giris_Tarihi DATE NOT NULL,
Cikis_Tarihi DATE NOT NULL,
Toplam_Ucret DECIMAL(10,2) NOT NULL,
FOREIGN KEY (Oda_ID) REFERENCES room(ID)
);




